In [1]:
# Linked List 
#  - Sequence of items (objects) where every item is lined to the next.
#  - Each element is dynamiclly allocated and in which elements points to each other.
#  - Elements are called nodes where each node has data and pointer to the next node.
#  - REquires more memory than array

# Real Time Problem
# Types of linked list
# 1.) Singly linked list
#     - It is one way sequences
# 2.) Doubly linked list
#     - It is two way sequences
# 3.) Circular Linked List
#     - The last node be indicated to the first node
# I)Steps to do the Singly linked list:
#    -> Create a node
#    -> Create a linked list
#    -> Operation of linked list 
#             |->Traverse
#             |->Insertion
#             |->Deletion
#
#
#
#
#
#
#
#
#
#
#

In [3]:
class User:
    def __init__(self, name, age, degree):
        self.name = name
        self.age = age
        self.degree = degree

    def display_info(self):
        print(f"Name: {self.name}")
        print(f"Age: {self.age}")
        print(f"Degree: {self.degree}")

name = input("Enter your name: ")
age = input("Enter your age: ")
degree = input("Enter your degree: ")

user = User(name, age, degree)
user.display_info()


Enter your name:  Sandra
Enter your age:  23
Enter your degree:  MCA


Name: Sandra
Age: 23
Degree: MCA


In [17]:
# ** Recursion **
#  - A technique where a function calls itself in order to solve a problem.
#  - The function repeats its process with a smaller 
# ** Baci  Structure of Recursion **
#  - Base Case : 
#  - Recursive Casre :
#  ** Example : Factorial**
#  The factorial function can be defined recursively as:
#   *  Factorial(n) = n*factorial(n-1) for n>1
#   *  Factorial(1) = 1 base case
#  
# def recursive_function(params):
#   # Base Case: condition to stop recursion
#    if condition:
#        return base_case_value
#    else:
#       #Recursive case: function calls itself with modified parameters
#       return recursive_function(modified_params)
#
#
#
#  ** Example:
#
#   * 1) Recursion
#
#     def factorial(n):
#       if n == 1:
#           return 1
#       else:
#           return n* factorial(n-1)
#
# Manuval Cal:-
#  n=5
#  fact(5) = 5*fact(4)   =>5x24 =120
#  fact(4) = 4*fact(3)   =>4x6 =24
#  fact(3) = 3*fact(2)   =>3x2 =6
#  fact(2) = 2*fact(1)   =>2x1 =2
#  fact(1) = 1*fact(0)   =>1 
#  fact(0) = 1
#
#   *2) Iteration 
#
#      def factorial(n):
#         result =1
#         for i in range(1, n+1):
#            result *= i
#         return result
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#


In [21]:
x=[
    [11,12,13],
    [21,22,23],
    [31,32,33]
]

#access of element of 2d array
op = x[1][2]
print(op)

#traverse all elements
for i in x:  # row
    for j in i:  # i th row traversal of j th column
        print(j, end="")
    print()

23
111213
212223
313233


In [31]:
x1=[
    [11,12,13],
    [21,22,23],
    [31,32,33]
]

x2=[
    [11,12,13],
    [21,22,23],
    [31,32,33]
]

result =[]
#matrix addition
for i in range(len(x1)):  # row
    row =[]
    for j in range(len(x1[0])):  # i th row traversal of j th column
        row.append(x1[i][j] + x2[i][j])
    result.append(row)
#print output
for i in result:
    for j in i:
        print(j, end=" ")
    print()

22 24 26 
42 44 46 
62 64 66 


In [37]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]], dtype=complex)

print(x)


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [39]:
y = np.ones((2,3), dtype = np.int32)
print(y)

[[1 1 1]
 [1 1 1]]


In [41]:
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
z = np.zeros((3,2))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [57]:
z = np.ones((3,2), dtype = [('m', 'int'),('n', 'float')])
print(z)

[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]


In [49]:
z = np.zeros((2,3), dtype = np.int32)
print(z)

[[0 0 0]
 [0 0 0]]


In [61]:
z = np.arange(1, 24, 2).reshape(3,4)
print(z)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [69]:
print("Row 0:", z[0])
print("Row 1:",  z[1])
print("Row -1:", z[-1])  # neggative indexing of row2


Row 0: [1 3 5 7]
Row 1: [ 9 11 13 15]
Row -1: [17 19 21 23]


In [71]:
#slicing operator
print(z[0:2])

[[ 1  3  5  7]
 [ 9 11 13 15]]


In [75]:
print(z[1:])

[[ 9 11 13 15]
 [17 19 21 23]]


In [79]:
print(z[::-1]) # reverse an array


[[17 19 21 23]
 [ 9 11 13 15]
 [ 1  3  5  7]]


In [83]:
#column access
print(z[:,0])

[ 1  9 17]


print("Column 0:", z[:,0])

In [90]:
print ("column 0" , z[:, 0])
print ("column 1" , z[:, 1])
print ("column 2" , z[:, -1])

column 0 [ 1  9 17]
column 1 [ 3 11 19]
column 2 [ 7 15 23]


In [92]:
#  New topic : 2d matrix additon

In [94]:
import numpy as np
x1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
x2 = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]])
result = x1 + x2
print(result)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]


In [11]:
import numpy as np
x1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
x2 = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]])
def matrix_addition(x1,x2):
    result = []
    for i in range(len(x1)):
        row = []
        for j in range(len(x1[0])):
            row.append((x1[i][j] + x2[i][j]))
        result.append(row)
    return(result)
#print (matrix_addition(x1,x2))
output = matrix_addition(x1,x2)
for i in output:
    print(i, end= " ")

[12, 24, 36] [48, 60, 72] [84, 96, 108] 

In [9]:
# Insertion new elements in a singly Linked List

# Code:

class node:
    def _in_it (self, Newdata=None,link=None):
        self.data = Newdata
        self.next = link
class singleLinkedList:
    def insert_begin(self, newData):
        self.Head=Node(newData, self.Head)


In [7]:
# Insertion new elements in a singly Linked List

# Code:

def insert_end(self,newData):
    newNode=Node(newData)
    if self.Head is None:
        self.Head = newNode
    else:
        curNode = self.Head
        while curNode.next is not None:
            curNode = curNode.next
        curNode.next = newNode